site_name: Gas Station Management
site_url: https://sawlwinnoo.github.io/Gas_Station_Management/
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: teal
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: teal
      accent: lime

plugins:
  - social

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/SawLwinnOo
#    - icon: fontawesome/brands/twitter
#      link: https://twitter.com/TheJamesWillett
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/saw-lwinn-oo-612511289/



copyright: |
  &copy; 2023 <a href="https://github.com/SawLwinnOo"  target="_blank" rel="noopener">Saw Lwinn Oo</a>